name: moj-bazzite
description: Personalizowany Bazzite - zoptymalizowany bez pobierania w locie
base-image: ghcr.io/ublue-os/bazzite-deck-nvidia
image-version: stable
modules:
  - type: rpm-ostree
    repos:
      - copr:mrduarte/LenovoLegionLinux
    install:
      - kleopatra
  - type: default-flatpaks
    configurations:
      - scope: user
        install:
          - com.brave.Browser       
          - net.davidotek.pupgui2   
  # 1. Kopiujemy gotowe RPM Kernela + akmods + kmods zbudowane W TYM SAMYM CZASIE
  - type: copy
    from: ghcr.io/vyzygota/akmods-nvidia-7.0:latest
    src: /rpms
    dest: /tmp/custom-rpms
  # 2. Instalujemy je jednym czystym poleceniem rpm-ostree
  - type: script
    snippets:
      - |
        echo "Finalna podmiana Kernela, Nvidii i modułu Lenovo..."
        
        # Opcjonalne włączanie repozytorium tylko do zależności GUI Lenovo
        dnf5 copr enable -y mrduarte/LenovoLegionLinux
        dnf5 install -y --disablerepo="rawhide" python-LenovoLegionLinux
        
        rpm-ostree override replace \
          --remove=kernel-devel-matched \
          --remove=kernel-modules-akmods \
          --remove=usbip \
          --remove=kernel-nvidia \
          /tmp/custom-rpms/kernel/*.rpm \
          /tmp/custom-rpms/akmods/*.rpm
        echo "Wpinanie surowych modułów Lenovo..."
        NEW_KERNEL=$(rpm -q --qf "%{VERSION}-%{RELEASE}.%{ARCH}\n" -p /tmp/custom-rpms/kernel/kernel-core-*.rpm | head -n 1)
        mkdir -p /usr/lib/modules/$NEW_KERNEL/extra/lenovo
        if ls /tmp/custom-rpms/kmods/*.ko 2>/dev/null; then
          cp /tmp/custom-rpms/kmods/*.ko /usr/lib/modules/$NEW_KERNEL/extra/lenovo/
        fi
        depmod -a $NEW_KERNEL
