name: bluebuild
on:
  schedule:
    - cron: "00 06 * * *"
  push:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml
    steps:
      - name: Build Custom Image 2
        uses: blue-build/github-action@v1.11
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          build_opts: "-vv"

  build-iso:
    name: Build and Upload to Google Drive
    runs-on: ubuntu-latest
    needs: bluebuild
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "today=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build ISO
        uses: jasonn3/build-container-installer@v1.2.2
        with:
          arch: x86_64
          image_name: moj-bazzite
          image_repo: ghcr.io/vyzygota
          image_tag: latest
          version: 43
          variant: Kinoite
          iso_name: moj-bazzite-${{ steps.date.outputs.today }}.iso

      # WYSYŁKA NA GOOGLE DRIVE
      - name: Upload ISO to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
          filename: ./moj-bazzite-${{ steps.date.outputs.today }}.iso
          folderId: ${{ secrets.GDRIVE_FOLDER_ID }}
          overwrite: "false"
